POST http://localhost:3001/users
Content-Type: application/json
{
    "firstName": "Bola",
    "lastName": "Tinubu",
    "age": 12,
    "address": "No.1 Africa, Nigeria",
    "guardianName": "Ahmed Tinubu",
    "guardianOccupation": "Businessman",
    "guardianEmail": "tbaba@gmail.com",
    "password": "baba@001"
}